/***************************************************************
*
* $RCSfile: XML_cdefBF541.h,v $
*
* Description: ADSP-BF541 CDEF Header
*
*              *************************
*              **  NON-EXISTANT PART  **
*              *************************
*
*              **************************************
*              **  AUTOMATICALLY GENERATED FILE!   **
*              **  DO NOT EDIT THIS FILE DIRECTLY  **
*              **************************************
*
* Copyright (c) 2006 Analog Devices Inc., All Rights Reserved
*
* $Log: XML_cdefBF541.h,v
*
***************************************************************/

#ifndef _XML_CDEF_BF541_H
#define _XML_CDEF_BF541_H

#endif /* _XML_CDEF_BF541_H */
