#!/bin/sh

USER=/home/test/work/cruise
CHECKOUT=$USER/checkouts
UBOOT_SCRIPTS=$USER/test_scripts/u-boot
UBOOT_SRC_ROOT=$CHECKOUT/u-boot

source $UBOOT_SCRIPTS/host_config.sh

UBOOT_SRC=$CHECKOUT/u-boot/
TIMESTAMP=`date +%Y_%m_%d_%H_%M`

cd $UBOOT_SCRIPTS/logs
rm -f *log test_results uboot.diff /tftpboot/u-boot.bin.* /tftpboot/u-boot.ldr.*
mv summary lastrun-summary

cp $CHECKOUT/u-boot/u-boot_test_script/*.exp $UBOOT_SCRIPTS
cp $CHECKOUT/u-boot/u-boot_test_script/uboot-test $UBOOT_SCRIPTS
cp $CHECKOUT/u-boot/u-boot_test_script/uboot_rectangle_test $UBOOT_SCRIPTS

cd $UBOOT_SCRIPTS
$UBOOT_SCRIPTS/uboot_misc_test.exp $BOARD_TYPE > /dev/null 2>&1

for TEST_ROUND in `seq 0 3`;
do
    $UBOOT_SCRIPTS/uboot-test $BOARD_TYPE $TEST_ROUND
    if [ $? != 2 ] ; then
        if [ -e /tftpboot/u-boot.bin ]; then
            mv -f /tftpboot/u-boot.bin /tftpboot/u-boot.bin.$TEST_ROUND
        fi
        if [ -e /tftpboot/u-boot.ldr ]; then
            mv -f /tftpboot/u-boot.ldr /tftpboot/u-boot.ldr.$TEST_ROUND
        fi
    fi
done

cd $UBOOT_SCRIPTS/logs
e=`ls *-summary-* | wc -l`
if [ $e != 0 ] ; then
    cat *-summary-* > summary
    svn info $UBOOT_SRC |grep "Revision" >> summary
fi
$UBOOT_SCRIPTS/compare_uboot_results lastrun-summary  summary > uboot.diff
if [ $? = 0 ] ; then
    echo  "success"  > test_results
    cat uboot.diff
    # echo  "Don't send email of uboot test."
else
    echo  "failed" > test_results
    echo
    cat uboot.diff
    cat summary
    # echo  "Sent email of uboot test."
fi

cd $UBOOT_SCRIPTS/logs
mkdir -p $UBOOT_SCRIPTS/logs/$TIMESTAMP
cp -fr *log test_results uboot.diff /tftpboot/u-boot.bin.* /tftpboot/u-boot.ldr.* $UBOOT_SCRIPTS/logs/$TIMESTAMP
cp -f summary $UBOOT_SCRIPTS/logs/$TIMESTAMP/summary
rm $UBOOT_SRC/u-boot.bin $UBOOT_SRC/u-boot.ldr
