#!/bin/sh
USER=~
CHECKOUT=$USER/checkouts
UBOOT_SCRIPTS=$USER/test_scripts/u-boot
SVN_SERVER=10.99.22.20

if [ $# -lt 1 ] ; then
echo  "Please input board_type [ change_clock_num ]. "
exit
fi

QUIT=2

## check out uboot
if [ ! -d $CHECKOUT ] ; then
  mkdir -p $CHECKOUT
fi
if [ ! -d $CHECKOUT/u-boot ] ; then
  mkdir -p $CHECKOUT/u-boot
fi

if [ $1 == "BF533-STAMP" ] ; then
     config_param=bf533-stamp_config 
elif [ $1 == "BF537-STAMP" ] ; then
     config_param=bf537-stamp_config
elif [ $1 = "BF561-EZKIT" ] ; then
     config_param=bf561-ezkit_config
elif [ $1 = "BF533-EZKIT" ] ; then
     config_param=bf533-ezkit_config
elif [ $1 = "BF537-EZKIT" ] ; then
     config_param=bf537-ezkit_config
else
echo "Unknown target board type $BOARD_TYPE."
exit
fi
  cp $CHECKOUT/u-boot/u-boot_test_script/*.exp $UBOOT_SCRIPTS

  $UBOOT_SCRIPTS/change_clk.exp $1 $2 

  export PATH=/opt/uClinux/bfin-uclinux/bin:/opt/uClinux/bfin-elf/bin:/opt/uClinux/bfin-linux-uclibc/bin:$PATH
  echo "Start building u-boot..."
  cd $CHECKOUT/u-boot/u-boot-1.1.6
  make clean  1>/dev/null 2>/dev/null
  make mrproper  1>/dev/null 2>/dev/null
  make $config_param  1>/dev/null 2>/dev/null
  make  1>$UBOOT_SCRIPTS/uboot_make_log 2>$UBOOT_SCRIPTS/uboot_make_log
  cp u-boot.bin /tftpboot 
  echo "Network restart..." 
  cd $UBOOT_SCRIPTS
  ./network_restart.exp
  sleep 20
  echo "Start uboot test..." 
  ./uboot_erase.exp  

  sleep 10
  if [ -f $UBOOT_SCRIPTS/logs/summary ] ; then
       rm $UBOOT_SCRIPTS/logs/summary
  fi
  sleep 5

 
  cd $UBOOT_SCRIPTS
  ./test-uboot.exp  $1 on on  1>/dev/null 2>/dev/null
  sleep 500

  ./test-uboot.exp  $1 on off  1>/dev/null 2>/dev/null
  sleep 500

  ./test-uboot.exp  $1 off on  1>/dev/null 2>/dev/null
  sleep 500

  ./test-uboot.exp  $1 off off  1>/dev/null 2>/dev/null

  cat $UBOOT_SCRIPTS/logs/summary

  cd $UBOOT_SCRIPTS
  if $UBOOT_SCRIPTS/decide_uboot_standard ; then
  echo  "success" > $USER/test_scripts/test_result
  else
  echo  "test_failed" > $USER/test_scripts/test_result
  fi

  echo
  echo  "The test_result of this testing:     "
  echo
  cat $USER/test_scripts/test_result

  sleep 100
  
