#!/bin/sh
USER=/home/test/work/cruise
CHECKOUT=$USER/checkouts
UBOOT_SCRIPTS=$USER/test_scripts/u-boot

cd $UBOOT_SCRIPTS/logs
rm -f test*log test_results uboot.diff
mv summary lastrun-summary

$UBOOT_SCRIPTS/uboot-test  BF548-EZKIT 0 3
$UBOOT_SCRIPTS/uboot-test  BF548-EZKIT 1 3
$UBOOT_SCRIPTS/uboot-test  BF548-EZKIT 2 3
$UBOOT_SCRIPTS/uboot-test  BF548-EZKIT 3 3

  cd $UBOOT_SCRIPTS/logs
  e=`ls *-summary-* | wc -l`
  if [ $e != 0 ] ; then
  cat *-summary-* > summary
  fi
  $UBOOT_SCRIPTS/compare_uboot_results lastrun-summary  summary > uboot.diff 
  if [ $? = 0 ] ; then
  echo  "success"  > test_results
  cat uboot.diff
 # echo  "Don't send email of uboot test."
  else
  echo  "failed" > test_results
  echo
  cat uboot.diff
  cat summary
 # echo  "Sent email of uboot test."
  fi



