#!/bin/sh
USER=/home/test
WORK=/home/test/work/cruise
CHECKOUT=$WORK/checkouts
UBOOT_SCRIPTS=$WORK/test_scripts/u-boot

if [ $# -lt 1 ] ; then
echo  "Please input board_type [ change_clock_num ]. "
exit
fi

## check out uboot
if [ ! -d $CHECKOUT ] ; then
  mkdir -p $CHECKOUT
fi
if [ ! -d $CHECKOUT/u-boot ] ; then
  mkdir -p $CHECKOUT/u-boot
fi

if [ $1 == "BF533-STAMP" ] ; then
     config_param=bf533-stamp_config 
elif [ $1 == "BF537-STAMP" ] ; then
     config_param=bf537-stamp_config
elif [ $1 = "BF561-EZKIT" ] ; then
     config_param=bf561-ezkit_config
elif [ $1 = "BF533-EZKIT" ] ; then
     config_param=bf533-ezkit_config
elif [ $1 = "BF537-EZKIT" ] ; then
     config_param=bf537-ezkit_config
elif [ $1 = "BF548-EZKIT" ] ; then
     config_param=bf548-ezkit_config
else
echo "Unknown target board type $BOARD_TYPE."
exit 2
fi
  cp $CHECKOUT/u-boot/u-boot_test_script/*.exp $UBOOT_SCRIPTS

  $UBOOT_SCRIPTS/change_clk.exp $1 $2 $CHECKOUT >$UBOOT_SCRIPTS/uboot_make_log  2>&1

  export PATH=/opt/uClinux/bfin-uclinux/bin:/opt/uClinux/bfin-elf/bin:/opt/uClinux/bfin-linux-uclibc/bin:$PATH
  rm /tftpboot/u-boot.bin

  echo "Start building u-boot of $1 . Clock config is $2 ."
  cd $CHECKOUT/u-boot/u-boot-1.1.6
  make clean   >/dev/null  2>&1
  make mrproper  >/dev/null  2>&1
  make $config_param  >/dev/null  2>&1
  make  >> $UBOOT_SCRIPTS/uboot_make_log  2>&1
 
  if [ -e u-boot.bin ] ; then
    cp u-boot.bin /tftpboot
    cp u-boot.ldr /tftpboot
  else
    tail -100 $UBOOT_SCRIPTS/uboot_make_log
    exit 2 
  fi
 
  cd $UBOOT_SCRIPTS

  echo "Start uboot test..."
  ./uboot_erase.exp  >> $UBOOT_SCRIPTS/uboot_make_log  2>&1 
  sleep 500

  ./test-uboot.exp  $1 on on  >/dev/null  2>&1
  sleep 500

  ./test-uboot.exp  $1 on off >/dev/null  2>&1
  sleep 500

  ./test-uboot.exp  $1 off on >/dev/null  2>&1
  sleep 500

  ./test-uboot.exp  $1 off off >/dev/null  2>&1 

  sleep 100
  
  echo "Done." 
