#!/bin/sh
# Script to generate u-boot binaries for release

uboot_ver="1.1.6" # be nice to get this from somewhere automatically ...

set -e

jobs=$(grep -cs processor /proc/cpuinfo)
jobs=$((${jobs:-1} * 2))
make="make -j${jobs} -s"

buildit() {
	local bmode bmodeU suffix
	local board=$1
	shift

	for bmode in "$@" ; do
		bmodeU=$(echo ${bmode} | tr '[:lower:]' '[:upper:]')
		printf "${board}: ${bmode}: "

		${make} distclean

		sed -i \
			-e '/define[[:space:]]*BFIN_BOOT_MODE/s:[[:space:]][^[:space:]]*$: BFIN_BOOT_'${bmodeU}':' \
			include/configs/${board}.h
		${make} ${board}

		case ${bmode} in
			bypass) suffix=".bin";;
			*) suffix=".ldr";;
		esac
		mv u-boot${suffix} ../RELEASE/u-boot-${board}-${bmode}-${ver}${suffix}

		${make} distclean
	done

	[ -d .git ] \
		&& git checkout include/configs/${board}.h \
		|| svn revert -q include/configs/${board}.h
}

rm -rf ../RELEASE
mkdir ../RELEASE

ver=$(sed -e 's:[[:space:]]*(ADI-::' -e 's:)[[:space:]]*::' localversion-adi)

buildit bf527-ezkit para spi_master uart
buildit bf533-ezkit bypass
buildit bf533-stamp bypass spi_master
buildit bf537-stamp bypass spi_master uart
buildit bf548-ezkit para spi_master uart
buildit bf561-ezkit bypass

# finally, create a tarball of the source code
uboot="u-boot-${uboot_ver}-${ver}"
if [ -d .git ] ; then
	git-archive --prefix=${uboot}/ master | bzip2 > ../RELEASE/${uboot}.tar.bz2
else
	svn export . ../RELEASE/${uboot}
	tar jcf ../RELEASE/${uboot}.tar.bz2 -C ../RELEASE ${uboot}
	rm -rf ../RELEASE/${uboot}
fi

cd ../RELEASE
chmod a-x *

# we only release spi-master ldrs, so remove "_master" suffix
for f in *_master* ; do
	mv ${f} $(echo ${f} | sed 's:_master::')
done

du -b *
