#!/usr/bin/expect

proc usage {} {
    global argv0

    send_user "\nUsage:  $argv0  BOARD_TYPE [ NUM  VCO_MULT  CCLK_DIV  SCLK_DIV ] \n"
    send_user "\nBOARD_TYPE: BF533-STAMP BF537-STAMP BF561-EZKIT BF533-EZKIT BF537-EZKIT etc.\n"
    send_user "\n********************************************************************\n"
    send_user "\nFor BF533-STAMP (ExtClock=11.0592Mhz, CPU_MaxClock=500Mhz)  :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   497         82         45          1         6        \n"
    send_user "\n 1    99         49         36          4         8        \n"
    send_user "\n 2   497         33         45          1         15       \n"
    send_user "\n 3   398         79         36          1         5        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF537-STAMP (ExtClock=25Mhz, CPU-MaxClock=500Mhz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   500        125         20          1         4        \n"
    send_user "\n 1   100         50         16          4         8        \n"
    send_user "\n 2   500         50         20          1         10       \n"
    send_user "\n 3   200        100         16          2         4        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF533-EZKIT (ExtClock=27Mhz, CPU_MaxClock=600Mhz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   594        118         22          1         5        \n"
    send_user "\n 1   101         50         15          4         8        \n"
    send_user "\n 2   594         49         22          1        12        \n"
    send_user "\n 3   202        101         15          2         4        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF561-EZKIT (ExtClock=30Mhz, CPU_MaxClock=600Mhz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   600        100         20          1         6        \n"
    send_user "\n 1    97         48         13          4         8        \n"
    send_user "\n 2   600         50         20          1        12        \n"
    send_user "\n 3   195         97         13          2         4        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF548-EZKIT (ExtClock=30Mhz, CPU_MaxClock=600Mhz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   525        131         21          1         4        \n"
    send_user "\n 1   162         81         13          2         4        \n"
    send_user "\n 2   525         87         21          1         6        \n"
    send_user "\n 3   187         93         15          2         4        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF527-EZKIT (ExtClock=25Mhz, CPU_MaxClock=600Mhz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   525        131         21          1         4        \n"
    send_user "\n 1   100         50         16          4         8        \n"
    send_user "\n 2   600         50         24          1        12        \n"
    send_user "\n 3   200        100         16          2         4        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF518F-EZBRD (ExtCLK=25Mhz, CPU_MaxCLK=400Mhz, Max_SCLK=80MHz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   400         80         16          1         5        \n"
    send_user "\n 2   100         50          8          2         4        \n"
    send_user "\n 3   400         50         16          1         8        \n"
    send_user "\n 1   156         78         25          4         8        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF526-EZBRD (ExtCLK=25Mhz, CPU_MaxCLK=400Mhz, Max_SCLK=80MHz) :\n"
    send_user "\n NUM CCLK(Mhz)  SCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV  \n"
    send_user "\n 0   400         80         16          1         5        \n"
    send_user "\n 2   100         50          8          2         4        \n"
    send_user "\n 3   400         50         16          1         8        \n"
    send_user "\n 1   156         78         25          4         8        \n"
    send_user "\n********************************************************************\n"

    send_user "\n********************************************************************\n"
    send_user "\nFor BF609-EZKIT (ExtCLK=25Mhz, CPU_MaxCLK=500Mhz, Max_SCLK=200MHz) :\n"
    send_user "\n NUM CCLK(Mhz)  DCLK (Mhz)   VCO_MULT  CCLK_DIV  SCLK_DIV DCLK_DIV \n"
    send_user "\n 0   500         250         20          1         5      2  \n"
    send_user "\n 2   500         125         20          1         5      4  \n"
    send_user "\n 3   400         200         16          1         4      2  \n"
    send_user "\n 1   400         133         16          1         4      3  \n"
    send_user "\n 4   500   (125) 250         20          1         4      2  \n"
    send_user "\n 5   500   (80)  250         20          1         6      2  \n"
    send_user "\n********************************************************************\n"
    exit
}


set argc [llength $argv]
if { $argc < 1} {
    usage
}
set board_type       [lindex $argv 0]

set num              0
if { $argc > 1} {
    set num              [lindex $argv 1]
}

set checkout_path /home/test/checkouts
if { $argc > 2} {
    set checkout_path       [lindex $argv 2]
}

if { $board_type == "BF533-STAMP" } {
    set config_file bf533-stamp.h
        if { $num == "0" } {
            set vco_mult  45
            set cclk_div  1
            set sclk_div  6
        } elseif { $num == "1" } {
            set vco_mult  36
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  45
            set cclk_div  1
            set sclk_div  15
        } elseif { $num == "3" } {
            set vco_mult  36
            set cclk_div  1
            set sclk_div  5
        }
} elseif { $board_type == "BF537-STAMP" } {
    set config_file bf537-stamp.h
        if { $num == "0" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  4
        } elseif { $num == "1" } {
            set vco_mult  16
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  10
        } elseif { $num == "3" } {
            set vco_mult  16
            set cclk_div  2
            set sclk_div  4
        }
} elseif { $board_type == "BF537-EZKIT" } {
    set config_file bf537-ezkit.h
        if { $num == "0" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  5
        } elseif { $num == "1" } {
            set vco_mult  16
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  10
        } elseif { $num == "3" } {
            set vco_mult  16
            set cclk_div  2
            set sclk_div  4
        }

} elseif { $board_type == "BF533-EZKIT" } {
    set config_file bf533-ezkit.h
        if { $num == "0" } {
            set vco_mult  22
            set cclk_div  1
            set sclk_div  5
        } elseif { $num == "1" } {
            set vco_mult  15
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  22
            set cclk_div  1
            set sclk_div  12
        } elseif { $num == "3" } {
            set vco_mult  15
            set cclk_div  2
            set sclk_div  4
        }
} elseif { $board_type == "BF561-EZKIT" } {
    set config_file bf561-ezkit.h
        if { $num == "0" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  6
        } elseif { $num == "1" } {
            set vco_mult  13
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  12
        } elseif { $num == "3" } {
            set vco_mult  13
            set cclk_div  2
            set sclk_div  4
        }
} elseif { $board_type == "BF548-EZKIT" } {
    set config_file bf548-ezkit.h
        if { $num == "0" } {
            set vco_mult  21
            set cclk_div  1
            set sclk_div  4
        } elseif { $num == "1" } {
            set vco_mult  13
            set cclk_div  2
            set sclk_div  4
        } elseif { $num == "2" } {
            set vco_mult  21
            set cclk_div  1
            set sclk_div  6
        } elseif { $num == "3" } {
            set vco_mult  15
            set cclk_div  2
            set sclk_div  4
        }
} elseif { $board_type == "BF527-EZKIT" } {
    set config_file bf527-ezkit.h
        if { $num == "0" } {
            set vco_mult  21
            set cclk_div  1
            set sclk_div  4
        } elseif { $num == "1" } {
            set vco_mult  16
            set cclk_div  4
            set sclk_div  8
        } elseif { $num == "2" } {
            set vco_mult  24
            set cclk_div  1
            set sclk_div  12
        } elseif { $num == "3" } {
            set vco_mult  16
            set cclk_div  2
            set sclk_div  4
        }
} elseif { $board_type == "BF518F-EZBRD" } {
    set config_file bf518f-ezbrd.h
        if { $num == "0" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  5
        } elseif { $num == "1" } {
            set vco_mult  8
            set cclk_div  2
            set sclk_div  4
        } elseif { $num == "2" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  8
        } elseif { $num == "3" } {
            set vco_mult  25
            set cclk_div  4
            set sclk_div  8
        }
} elseif { $board_type == "BF526-EZBRD" } {
    set config_file bf526-ezbrd.h
        if { $num == "0" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  5
        } elseif { $num == "1" } {
            set vco_mult  8
            set cclk_div  2
            set sclk_div  4
        } elseif { $num == "2" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  8
        } elseif { $num == "3" } {
            set vco_mult  25
            set cclk_div  4
            set sclk_div  8
        }
} elseif { $board_type == "BF609-EZKIT" } {
    set config_file bf609-ezkit.h
        if { $num == "0" } {
            set vco_mult  20 
            set cclk_div  1
            set sclk_div  5
            set dclk_div  2
        } elseif { $num == "1" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  5
            set dclk_div  4
        } elseif { $num == "2" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  4
            set dclk_div  2
        } elseif { $num == "3" } {
            set vco_mult  16
            set cclk_div  1
            set sclk_div  4
            set dclk_div  3
        } elseif { $num == "4" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  4
            set dclk_div  2
        } elseif { $num == "5" } {
            set vco_mult  20
            set cclk_div  1
            set sclk_div  6
            set dclk_div  2
        }
} else {
    send_user "\n Unknown target board type.\n"
    exit
}

if { $argc > 5} {
    set vco_mult         [lindex $argv 3]
    set cclk_div         [lindex $argv 4]
    set sclk_div         [lindex $argv 5]
    send_user "VCO_MULT: $vco_mult ,CCLK_DIV: $cclk_div , SCLK_DIV $sclk_div\n"
}


if { $argc > 6} {
    set dclk_div         [lindex $argv 6]
    send_user "DCLK_DIV: $dclk_div \n"
}

cd $checkout_path
sleep 3
set timeout 2
spawn ex include/configs/$config_file
expect {
    "Entering Ex mode*Normal mode." { }

    "already exists!" {
        send "e\r"
        sleep 1
    }
}
sleep 1
send "/#define *CONFIG_VCO_MULT\r"
expect "#define *CONFIG_VCO_MULT"
send "d\r"
expect ":"
send "i\r"
sleep .5
send "#define CONFIG_VCO_MULT                   $vco_mult\r"
sleep .5
send ".\r"
expect ":"

send "/#define *CONFIG_CCLK_DIV\r"
expect "#define *CONFIG_CCLK_DIV"
send "d\r"
expect ":"
send "i\r"
sleep .5
send "#define CONFIG_CCLK_DIV                   $cclk_div\r"
sleep .5
send ".\r"
expect ":"

send "/#define *CONFIG_SCLK_DIV\r"
expect "#define *CONFIG_SCLK_DIV"
send "d\r"
expect ":"
send "i\r"
sleep .5
send "#define CONFIG_SCLK_DIV                   $sclk_div\r"
sleep .5
send ".\r"
expect ":"

if { $board_type == "BF609-EZKIT" } {
send "/#define *CONFIG_DCLK_DIV\r"
expect "#define *CONFIG_DCLK_DIV"
send "d\r"
expect ":"
send "i\r"
sleep .5
send "#define CONFIG_DCLK_DIV                   $dclk_div\r"
sleep .5
send ".\r"
expect ":"
}

send "wq\r"
expect eof
