#!/usr/bin/expect
log_file change_conf_log
proc usage {} {
    global argv0

    send_user "\nUsage:  $argv0  BOARD_TYPE SEARCH_STR CHANGE_STR\n"
    send_user "\nBOARD_TYPE: BF533-STAMP BF537-STAMP BF561-EZKIT BF533-EZKIT BF537-EZKIT etc.\n"
    exit 1
}
set PWD [exec pwd]
send_user "!!!!!!!!!! $PWD \n"
cd test_script
source uboot-config.exp

set argc [llength $argv]
if { $argc < 3} {
    usage
}

set board_type [lindex $argv 0]
set search_str [lindex $argv 1]
set change_str [lindex $argv 2]

if { $board_type == "BF533-STAMP" } {
    set config_file bf533-stamp.h
} elseif { $board_type == "BF537-STAMP" } {
    set config_file bf537-stamp.h
} elseif { $board_type == "BF537-EZKIT" } {
    set config_file bf537-ezkit.h
} elseif { $board_type == "BF533-EZKIT" } {
    set config_file bf533-ezkit.h
} elseif { $board_type == "BF561-EZKIT" } {
    set config_file bf561-ezkit.h
} elseif { $board_type == "BF548-EZKIT" } {
    set config_file bf548-ezkit.h
} elseif { $board_type == "BF527-EZKIT" } {
    set config_file bf527-ezkit.h
} elseif { $board_type == "BF518F-EZBRD" } {
    set config_file bf518f-ezbrd.h
} elseif { $board_type == "BF526-EZBRD" } {
    set config_file bf526-ezbrd.h
} elseif { $board_type == "BF609-EZKIT" } {
    set config_file bf609-ezkit.h
} else {
    send_user "\n Unknown target board type.\n"
    exit 1
}


cd $uboot_test_loc
send_user "########## $uboot_test_loc \n"
spawn ex include/configs/$config_file
expect {
    "Entering Ex mode*Normal mode." { }

    "already exists!" {
        send "e\r"
        sleep 1
    }
}
sleep 1
send "/$search_str\r"
expect "$search_str"
send "d\r"
expect ":"
send "i\r"
sleep .5
send "$change_str\r"
sleep .5
send ".\r"
expect ":"
send "wq\r"
expect eof

exit 0
log_file
