#!/bin/bash

echo "Starting $0 ! $1 $2 !!"
if [ $# -lt 1 ] ; then
    echo  "Please input board_type [ change_clock_num ]. "
    exit
fi

## check out uboot

if [ $1 = "BF533-STAMP" ] ; then
    config_param=bf533-stamp_config
elif [ $1 = "BF537-STAMP" ] ; then
    config_param=bf537-stamp_config
elif [ $1 = "BF561-EZKIT" ] ; then
    config_param=bf561-ezkit_config
elif [ $1 = "BF533-EZKIT" ] ; then
    config_param=bf533-ezkit_config
elif [ $1 = "BF537-EZKIT" ] ; then
    config_param=bf537-ezkit_config
elif [ $1 = "BF548-EZKIT" ] ; then
    config_param=bf548-ezkit_config
elif [ $1 = "BF527-EZKIT" ] ; then
    config_param=bf527-ezkit_config
elif [ $1 = "BF518F-EZBRD" ] ; then
    config_param=bf518f-ezbrd_config
elif [ $1 = "BF526-EZBRD" ] ; then
    config_param=bf526-ezbrd_config
elif [ $1 = "BF609-EZKIT" ] ; then
    config_param=bf609-ezkit_config
else
    echo "Unknown target board type $BOARD_TYPE."
    exit 2
fi

if [ $# -gt 1 ] ; then
    $UBOOT_SCRIPTS/change_clk.exp $1 $2 $UBOOT_SRC >$UBOOT_SCRIPTS/uboot_make_log  2>&1
fi

if [ $# -gt 2 ] ; then
    $UBOOT_SCRIPTS/boot_config.exp $1 $3 $UBOOT_SRC >$UBOOT_SCRIPTS/uboot_make_log  2>&1
fi

export PATH=/opt/uClinux/bfin-uclinux/bin:/opt/uClinux/bfin-elf/bin:/opt/uClinux/bfin-linux-uclibc/bin:$PATH
rm -f /tftpboot/u-boot.bin

echo "Start building u-boot of $1 . Clock config is $2 ."
cd $UBOOT_SRC
make distclean   >/dev/null  2>&1
make clean   >/dev/null  2>&1
make mrproper  >/dev/null  2>&1
make $config_param  >/dev/null  2>&1
make  >> $UBOOT_SCRIPTS/uboot_make_log  2>&1

[ -e u-boot.bin ] && cp u-boot.bin /tftpboot 
[ -e u-boot.ldr ] && cp u-boot.ldr /tftpboot 

if [ ! -e u-boot.bin ] && [ ! -e u-boot.ldr ] ; then
    tail -100 $UBOOT_SCRIPTS/uboot_make_log
    exit 2
fi

cd $UBOOT_SCRIPTS

echo "Start uboot test..."
./uboot_erase.exp  >> $UBOOT_SCRIPTS/uboot_make_log  2>&1
sleep 100

./test-uboot.exp  $1 on on  >/dev/null  2>&1
sleep 100

./test-uboot.exp  $1 on off >/dev/null  2>&1
sleep 100

./test-uboot.exp  $1 off on >/dev/null  2>&1
sleep 100

./test-uboot.exp  $1 off off >/dev/null  2>&1

sleep 100

echo "Done."
